name: kurs-cron
on:
  schedule:
    - cron: '01 10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://vercel-utz0r2.vercel.app/api/kurs'